angular.module('packages-ui', [
	//vendor stuff
	'ui.bootstrap',
	'ui.router',
	'hc.marked',
	'btford.socket-io',
	'luegg.directives',
	//autogenerated
	'templates',
	//our stuff
	'packages',
	'browser',
	'scripts',
	'player'
]);
